# Generated by Django 4.0 on 2022-04-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_remove_post_photo_url_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='is_confirmed',
        ),
    ]
